# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/ji/20 Fall/ve370/project_2_pipeline/project_2_pipeline.cache/wt} [current_project]
set_property parent.project_path {D:/ji/20 Fall/ve370/project_2_pipeline/project_2_pipeline.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/ji/20 Fall/ve370/project_2_pipeline/project_2_pipeline.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {D:/ji/20 Fall/ve370/project_2_pipeline/project_2_pipeline.srcs/sources_1/new/ALU.v}
  {D:/ji/20 Fall/ve370/project_2_pipeline/project_2_pipeline.srcs/sources_1/new/ALU_control.v}
  {D:/ji/20 Fall/ve370/project_2_pipeline/project_2_pipeline.srcs/sources_1/new/Control.v}
  {D:/ji/20 Fall/ve370/project_2_pipeline/project_2_pipeline.srcs/sources_1/new/EX_MEM.v}
  {D:/ji/20 Fall/ve370/project_2_pipeline/project_2_pipeline.srcs/sources_1/new/Hazard_Detection.v}
  {D:/ji/20 Fall/ve370/project_2_pipeline/project_2_pipeline.srcs/sources_1/new/ID_EX.v}
  {D:/ji/20 Fall/ve370/project_2_pipeline/project_2_pipeline.srcs/sources_1/new/IF_ID.v}
  {D:/ji/20 Fall/ve370/project_2_pipeline/project_2_pipeline.srcs/sources_1/new/Instruction_Memory.v}
  {D:/ji/20 Fall/ve370/project_2_pipeline/project_2_pipeline.srcs/sources_1/new/MEM_WB.v}
  {D:/ji/20 Fall/ve370/project_2_pipeline/project_2_pipeline.srcs/sources_1/new/Mux_3_1_32bit.v}
  {D:/ji/20 Fall/ve370/project_2_pipeline/project_2_pipeline.srcs/sources_1/new/PC.v}
  {D:/ji/20 Fall/ve370/project_2_pipeline/project_2_pipeline.srcs/sources_1/new/clock_divider.v}
  {D:/ji/20 Fall/ve370/project_2_pipeline/project_2_pipeline.srcs/sources_1/new/counter_ring_4.v}
  {D:/ji/20 Fall/ve370/project_2_pipeline/project_2_pipeline.srcs/sources_1/new/data_memory.v}
  {D:/ji/20 Fall/ve370/project_2_pipeline/project_2_pipeline.srcs/sources_1/new/forwarding_unit.v}
  {D:/ji/20 Fall/ve370/project_2_pipeline/project_2_pipeline.srcs/sources_1/new/fourbit_ssd_num.v}
  {D:/ji/20 Fall/ve370/project_2_pipeline/project_2_pipeline.srcs/sources_1/new/pipeline.v}
  {D:/ji/20 Fall/ve370/project_2_pipeline/project_2_pipeline.srcs/sources_1/new/register.v}
  {D:/ji/20 Fall/ve370/project_2_pipeline/project_2_pipeline.srcs/sources_1/new/sign_extention.v}
  {D:/ji/20 Fall/ve370/project_2_pipeline/project_2_pipeline.srcs/sources_1/new/p2.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/ji/20 Fall/ve370/project_2_pipeline/project_2_pipeline.srcs/constrs_1/new/p2.xdc}}
set_property used_in_implementation false [get_files {{D:/ji/20 Fall/ve370/project_2_pipeline/project_2_pipeline.srcs/constrs_1/new/p2.xdc}}]


synth_design -top p2 -part xc7a35tcpg236-1


write_checkpoint -force -noxdef p2.dcp

catch { report_utilization -file p2_utilization_synth.rpt -pb p2_utilization_synth.pb }
